blank_issues_enabled: false
contact_links:
  - name: Feature Request or Idea
    url: https://github.com/mishkamartinmakworx/VoiceLite/discussions
    about: Please post feature requests and ideas in our Discussions tab
  - name: General Discussion
    url: https://github.com/mishkamartinmakworx/VoiceLite/discussions
    about: Ask questions and discuss VoiceLite with the community
