markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v1
  prdSharded: false
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v1
  architectureSharded: false
  architectureShardedLocation: docs/architecture
customTechnicalDocuments:
  - CLAUDE.md
devLoadAlwaysFiles:
  - CLAUDE.md
devDebugLog: .bmad-core/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
